version: "3.0"
services:

  server:
    container_name: server
    build: 
      context: .
      dockerfile: "./Dockerfile"
    
    stdin_open: true
    tty: true 
    cap_add:
    - NET_ADMIN


  client:
    container_name: client
    build: 
      context: .
      dockerfile: "./Dockerfile"

    stdin_open: true
    tty: true
    cap_add:
    - NET_ADMIN
